/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JPanel;

/**
 *
 * @author hoanglong
 */
public class DrawWithMouse extends javax.swing.JFrame {

    Graphics g = null;
    Point p1 = null, p2 = null;
    Color color = Color.RED;
    LinePanel lp = new LinePanel(color);
    boolean type = true;
    EclipsePanel ep = new EclipsePanel(type, color);
    ReactanglePanel rp = new ReactanglePanel(type, color);
    int index;

    public DrawWithMouse() {

        initComponents();
        //g = this.pLine.getGraphics();
        this.pLine.add(lp);
        lp.setSize(1366, 768);
        this.rdFill.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnSelect = new javax.swing.JButton();
        rdDraw = new javax.swing.JRadioButton();
        rdFill = new javax.swing.JRadioButton();
        jtabbed = new javax.swing.JTabbedPane();
        pLine = new javax.swing.JPanel();
        pEclipse = new javax.swing.JPanel();
        pReactangle = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSelect.setText("Select color");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelect);

        buttonGroup1.add(rdDraw);
        rdDraw.setSelected(true);
        rdDraw.setText("Draw");
        rdDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDrawActionPerformed(evt);
            }
        });
        jPanel1.add(rdDraw);

        buttonGroup1.add(rdFill);
        rdFill.setText("Draw and fill");
        rdFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFillActionPerformed(evt);
            }
        });
        jPanel1.add(rdFill);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jtabbed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabbedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pLineLayout = new javax.swing.GroupLayout(pLine);
        pLine.setLayout(pLineLayout);
        pLineLayout.setHorizontalGroup(
            pLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pLineLayout.setVerticalGroup(
            pLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        jtabbed.addTab("Lines", pLine);

        javax.swing.GroupLayout pEclipseLayout = new javax.swing.GroupLayout(pEclipse);
        pEclipse.setLayout(pEclipseLayout);
        pEclipseLayout.setHorizontalGroup(
            pEclipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pEclipseLayout.setVerticalGroup(
            pEclipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        jtabbed.addTab("Eclipses", pEclipse);

        javax.swing.GroupLayout pReactangleLayout = new javax.swing.GroupLayout(pReactangle);
        pReactangle.setLayout(pReactangleLayout);
        pReactangleLayout.setHorizontalGroup(
            pReactangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pReactangleLayout.setVerticalGroup(
            pReactangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        jtabbed.addTab("Reactangle", pReactangle);

        getContentPane().add(jtabbed, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        color = JColorChooser.showDialog(this, "Choose a color", Color.BLACK);
        //g.setColor(color);
        lp.makeColor(color);
        ep.makeColor(color);
        rp.makeColor(color);
    }//GEN-LAST:event_btnSelectActionPerformed

    private void jtabbedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabbedMouseClicked
        index = this.jtabbed.getSelectedIndex();
        switch (index) {
            case 0:
                this.pLine.add(lp);
                lp.setSize(1366, 768);
                //this.rdDraw.setSelected(true);
                //this.rdFill.setSelected(false);
                break;
            case 1: {

                this.rdFill.setEnabled(true);
                //rdFill.setSelected(true);
                if (type == true) {
                    //type = true;
                    ep.makeType(type);
                    this.pEclipse.add(ep);
                }
                if (type == false) {
                    //type = false;
                    ep.makeType(type);
                    this.pEclipse.add(ep);
                }
                ep.setSize(1366, 768);

            }
            break;
            case 2:
                this.rdFill.setEnabled(true);
                //rdFill.setSelected(true);
                if (type == true) {
                    //type = true;
                    rp.makeType(type);
                    this.pReactangle.add(rp);
                }
                if (type == false) {
                    //type = false;
                    rp.makeType(type);
                    this.pReactangle.add(rp);
                }
                rp.setSize(1366, 768);
                break;
        }
    }//GEN-LAST:event_jtabbedMouseClicked

    private void rdFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFillActionPerformed
        if (this.rdFill.isSelected()) {
            type = false;
            index = jtabbed.getSelectedIndex();
            jtabbedMouseClicked(null);
        }
    }//GEN-LAST:event_rdFillActionPerformed

    private void rdDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDrawActionPerformed
        if (this.rdDraw.isSelected()) {
            type = true;
            index = jtabbed.getSelectedIndex();
            jtabbedMouseClicked(null);
        }
    }//GEN-LAST:event_rdDrawActionPerformed

    private ArrayList<Point> points = new ArrayList<Point>();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawWithMouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jtabbed;
    private javax.swing.JPanel pEclipse;
    private javax.swing.JPanel pLine;
    private javax.swing.JPanel pReactangle;
    private javax.swing.JRadioButton rdDraw;
    private javax.swing.JRadioButton rdFill;
    // End of variables declaration//GEN-END:variables

}
