/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;

/**
 *
 * @author hoanglong
 */
public class LinePanel extends javax.swing.JPanel {

    Point p1 = null;
    Point p2 = null;
    Color color;
    private ArrayList<Point> points = new ArrayList<Point>();
    private ArrayList<Color> mau = new ArrayList<Color>();

    public LinePanel(Color color) {
        initComponents();
        this.color = color;
    }

    public void makeColor(Color color) {
        this.color = color;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        p1 = evt.getPoint();
        p2 = p1;
        points.add(p1);
        mau.add(color);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        p2 = evt.getPoint();
        points.add(p2);
        mau.add(color);
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        p2 = evt.getPoint();
        //this.getGraphics().drawLine(p1.x, p1.y, p2.x, p2.y);
        repaint();
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // p2 = evt.getPoint();

    }//GEN-LAST:event_formMouseMoved

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        {
            if (p1 != null) {
                g.setColor(color);
                g.drawLine(p1.x, p1.y, p2.x, p2.y);
            }

            if (points.size() >= 2) {
                for (int i = 0; i < points.size() - 2; i++) {
                    if (i % 2 == 0) {
                        g.setColor(mau.get(i));
                        Point p3 = points.get(i);
                        Point p4 = points.get(i + 1);
                        g.drawLine(p3.x, p3.y, p4.x, p4.y);
                    }
                    //g.drawLine(p1.x, p1.y, p2.x, p2.y);
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
